name: IaC Pipeline - Cost Estimation

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  cost-estimation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Gera o relatório comparando o código da branch atual com a branch principal (main)
      - name: Gerar Análise de Custos Comparativa
        run: |
          infracost breakdown --path=infra \
                              --format=json \
                              --out-file=/tmp/infracost.json

      - name: Postar Comentário no PR
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update
          show-skipped: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
